name: CI
on: 
  pull_request:
    braches:
      - master
      - deploy 

jobs:
  flutter_analyze:
    name: Analyze Flutter code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.1'
      - run: flutter pub get
      - run: flutter analyze  

  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2 
        with:
          distribution: 'adopt' 
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with: 
          flutter-version: '3.0.1'
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

  build_appbundle:
    name: Build Flutter (Android)
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2 
        with: 
          distribution: 'adopt'
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with: 
          flutter-version: '3.0.1'
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build appbundle



      